project:
  type: website

website:
  title: "Analytics"
  navbar:
    left:
    - text: "ISSS608 VAA"
    menu: 
      - text: "VAA Portfolio"
        href: "vaa_portfolio.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

