project:
  type: website

website:
  title: "Analytics"
  navbar:
    left:
    - text: "ISSS608 VAA"
      href: ISSS608/vaa_portfolio.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

